### ISSUE TITLE
InstallationError:   option --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by daamien** [chdemko/pandoc-latex-tip#1]
Hi !

I'd like to try the pandoc-latex-tip filter but the install process fails when I run 

```
 sudo apt-get build-dep python-imaging
 sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
 sudo  pip install pandoc-latex-tip
```

I get the following error:

```
Installing collected packages: pandoc-latex-tip, icon-font-to-png, pillow, appdirs, requests, six, tinycss
  Running setup.py install for pandoc-latex-tip
    Running command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hyxieD/pandoc-latex-tip/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FAaDPZ-record/install-record.txt --single-version-externally-managed --compile
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hyxieD/pandoc-latex-tip/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FAaDPZ-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: option --single-version-externally-managed not recognized

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hyxieD/pandoc-latex-tip/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FAaDPZ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-hyxieD/pandoc-latex-tip
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 309, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hyxieD/pandoc-latex-tip/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FAaDPZ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-hyxieD/pandoc-latex-tip
```

I get the same error on Ubuntu Willy,  Ubuntu Xenial and Debian Jessie

**Comment by chdemko** [comment]
What is your python version?

**Comment by daamien** [comment]
```
$ python -V
Python 2.7.12
$ pip -V
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by daamien** [comment]
same error with pip3/python3

```
  Running setup.py install for pandoc-latex-tip ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cqmdedij/pandoc-latex-tip/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gngh76i9-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cqmdedij/pandoc-latex-tip/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gngh76i9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cqmdedij/pandoc-latex-tip/   
```

**Comment by daamien** [comment]
the --egg option solved the problem 

```
sudo  pip install --egg pandoc-latex-tip   
```

No idea why

Anyway many thanks for your pandoc filters ! We're currently building a complete set of PostgreSQL training courses in French and your plugins are part of the production toolchain.

**Comment by chdemko** [comment]
Je suis preneur...

**Comment by daamien** [comment]
UPDATE : The solutions above is a bad idea. The --egg option skips the creation of the binary entry point ( ``/usr/local/bin/pandoc-latex-tip`` ) and then you can't use the filter with ``pandoc --filter pandoc-latex-tip`` because pandoc can't find the entrypoint.

The proper solution is to reinstall again without the --egg option:

```
sudo -H pip install pandoc-latex-tip --egg
sudo -H pip install pandoc-latex-tip
```
