### ISSUE TITLE
pip install error on centos 7.6

### ISSUE THREAD

**Issue by tigerfoot** [chdemko/pandoc-latex-tip#11]
Hi I was trying to use pandoc-latex-tip in a centos 7.6 pip venv (with python36 installed)
and I get errors like the following

```
pip install --upgrade --force --no-cache git+https://github.com/chdemko/pandoc-latex-tip
Collecting git+https://github.com/chdemko/pandoc-latex-tip
  Cloning https://github.com/chdemko/pandoc-latex-tip to /tmp/pip-req-build-ly3qsv54
Collecting panflute>=1.10 (from pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/69/32/ce08857e6ecea018836d3f8e8661a61eca6f6285c6bf963d854d7e1bfbad/panflute-1.11.2-py3-none-any.whl
Collecting icon_font_to_png>=0.4 (from pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/3d/70/c3b6c5904ae8592cb97c3ddb5de40801837f66922aa140e285d4a2e49a42/icon_font_to_png-0.4.1-py2.py3-none-any.whl (161kB)
    100% |████████████████████████████████| 163kB 20.7MB/s
Collecting pillow>=5.2 (from pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/85/5e/e91792f198bbc5a0d7d3055ad552bc4062942d27eaf75c3e2783cf64eae5/Pillow-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 18.8MB/s
Collecting appdirs>=1.4 (from pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting pypandoc>=1.4 (from pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz
Collecting requests>=2 (from pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 1.4MB/s
Collecting pyyaml (from panflute>=1.10->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/9f/2c/9417b5c774792634834e730932745bc09a7d36754ca00acf1ccd1ac2594d/PyYAML-5.1.tar.gz (274kB)
    100% |████████████████████████████████| 276kB 2.3MB/s
Collecting future (from panflute>=1.10->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 15.2MB/s
Collecting click (from panflute>=1.10->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 1.9MB/s
Collecting shutilwhich (from panflute>=1.10->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/66/be/783f181594bb8bcfde174d6cd1e41956b986d0d8d337d535eb2555b92f8d/shutilwhich-1.1.0.tar.gz
Collecting six>=1.10.0 (from icon_font_to_png>=0.4->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tinycss>=0.4 (from icon_font_to_png>=0.4->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/05/59/af583fff6236c7d2f94f8175c40ce501dcefb8d1b42e4bb7a2622dff689e/tinycss-0.4.tar.gz (87kB)
    100% |████████████████████████████████| 92kB 2.1MB/s
Collecting setuptools (from pypandoc>=1.4->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 38.2MB/s
Collecting pip>=8.1.0 (from pypandoc>=1.4->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 12.7MB/s
Collecting wheel>=0.25.0 (from pypandoc>=1.4->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 13.9MB/s
Collecting urllib3<1.25,>=1.21.1 (from requests>=2->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 2.1MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 2.6MB/s
Collecting idna<2.9,>=2.5 (from requests>=2->pandoc-latex-tip==2.1.0)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 12.5MB/s
Installing collected packages: pyyaml, future, click, shutilwhich, panflute, six, pillow, tinycss, certifi, urllib3, chardet, idna, requests, icon-font-to-png, appdirs, setuptools, pip, wheel, pypandoc, pandoc-latex-tip
  Found existing installation: PyYAML 5.1
    Uninstalling PyYAML-5.1:
      Successfully uninstalled PyYAML-5.1
  Running setup.py install for pyyaml ... done
  Found existing installation: future 0.17.1
    Uninstalling future-0.17.1:
      Successfully uninstalled future-0.17.1
  Running setup.py install for future ... done
  Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
  Found existing installation: shutilwhich 1.1.0
    Uninstalling shutilwhich-1.1.0:
      Successfully uninstalled shutilwhich-1.1.0
  Running setup.py install for shutilwhich ... done
  Found existing installation: panflute 1.11.2
    Uninstalling panflute-1.11.2:
      Successfully uninstalled panflute-1.11.2
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
  Found existing installation: Pillow 5.4.1
    Uninstalling Pillow-5.4.1:
      Successfully uninstalled Pillow-5.4.1
  Found existing installation: tinycss 0.4
    Uninstalling tinycss-0.4:
      Successfully uninstalled tinycss-0.4
  Running setup.py install for tinycss ... done
  Found existing installation: certifi 2019.3.9
    Uninstalling certifi-2019.3.9:
      Successfully uninstalled certifi-2019.3.9
  Found existing installation: urllib3 1.24.1
    Uninstalling urllib3-1.24.1:
      Successfully uninstalled urllib3-1.24.1
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Found existing installation: idna 2.8
    Uninstalling idna-2.8:
      Successfully uninstalled idna-2.8
  Found existing installation: requests 2.21.0
    Uninstalling requests-2.21.0:
      Successfully uninstalled requests-2.21.0
  Found existing installation: icon-font-to-png 0.4.1
    Uninstalling icon-font-to-png-0.4.1:
      Successfully uninstalled icon-font-to-png-0.4.1
  Found existing installation: appdirs 1.4.3
    Uninstalling appdirs-1.4.3:
      Successfully uninstalled appdirs-1.4.3
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
  Found existing installation: wheel 0.33.1
    Uninstalling wheel-0.33.1:
      Successfully uninstalled wheel-0.33.1
  Found existing installation: pypandoc 1.4
    Uninstalling pypandoc-1.4:
      Successfully uninstalled pypandoc-1.4
  Running setup.py install for pypandoc ... done
  Running setup.py install for pandoc-latex-tip ... error
    Complete output from command /var/tmp/pandoc-venv/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ly3qsv54/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d1lpozjc/install-record.txt --single-version-externally-managed --compile --install-headers /var/tmp/pandoc-venv/include/site/python3.6/pandoc-latex-tip:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying pandoc_latex_tip.py -> build/lib
    Running post build task
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ly3qsv54/setup.py", line 280, in <module>
        tests_require=["pytest"],
      File "/var/tmp/pandoc-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/var/tmp/pandoc-venv/lib64/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-ly3qsv54/setup.py", line 200, in run
        self.execute(_post, (), msg="Running post build task")
      File "/usr/lib64/python3.6/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/util.py", line 301, in execute
        func(*args)
      File "/tmp/pip-req-build-ly3qsv54/setup.py", line 39, in _post
        _post_fontawesome_47()
      File "/tmp/pip-req-build-ly3qsv54/setup.py", line 47, in _post_fontawesome_47
        directory = _directory("fontawesome", "4.7")
      File "/tmp/pip-req-build-ly3qsv54/setup.py", line 175, in _directory
        get_distribution("pandoc_latex_tip").version,
      File "/var/tmp/pandoc-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
        dist = get_provider(dist)
      File "/var/tmp/pandoc-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 357, in get_provider
        return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
      File "/var/tmp/pandoc-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/var/tmp/pandoc-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pandoc_latex_tip' distribution was not found and is required by the application

    ----------------------------------------
Command "/var/tmp/pandoc-venv/bin/python36 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ly3qsv54/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d1lpozjc/install-record.txt --single-version-externally-managed --compile --install-headers /var/tmp/pandoc-venv/include/site/python3.6/pandoc-latex-tip" failed with error code 1 in /tmp/pip-req-build-ly3qsv54/

```

Any idea about what's happening, I'm clueless about what fail.

**Comment by tigerfoot** [comment]
ok it seems I'm having a quite restricted environment with limited access to internet.
while pip support quite well the proxy used, the _post part of setup.py seems to not support the proxy.

**Comment by chdemko** [comment]
If you solved the issue in the code, a pull request is welcomed.

**Comment by tigerfoot** [comment]
Sorry no real solutions, was a hack (commented out all _post) and do it by hands :-(
