### ISSUE TITLE
Throws an exception when inserting a table

### ISSUE THREAD

**Issue by eliedrian** [chdemko/pandoc-latex-tip#13]
When I insert a table pandoc-latex-tip throws an exception of an unknown tag "Caption"

```
Traceback (most recent call last):
  File "/home/tan/.local/bin/pandoc-latex-tip", line 33, in <module>
    sys.exit(load_entry_point('pandoc-latex-tip==2.1.6', 'console_scripts', 'pandoc-latex-tip')())
  File "/home/tan/.local/lib/python3.8/site-packages/pandoc_latex_tip.py", line 559, in main
    return run_filter(_tip, prepare=_prepare, finalize=_finalize, doc=doc)
  File "/home/tan/.local/lib/python3.8/site-packages/panflute/io.py", line 266, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/home/tan/.local/lib/python3.8/site-packages/panflute/io.py", line 239, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/tan/.local/lib/python3.8/site-packages/panflute/io.py", line 59, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/tan/.local/lib/python3.8/site-packages/panflute/elements.py", line 1532, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Caption
Error running filter pandoc-latex-tip:
Filter returned error status 1
```
I'm running pandoc with just this filter to see whether it's interaction with other filters, it still errors out. When I remove the table it runs fine.

**Comment by chdemko** [comment]
See https://github.com/sergiocorreia/panflute/issues/142
