### ISSUE TITLE
res = action(item['t'], item['c'], format, meta) returns KeyError: 'c'

### ISSUE THREAD

**Issue by daamien** [chdemko/pandoc-latex-tip#4]
Found another problem similar to the previous one

```
$ pandoc tests/pandoc-latex-tip-sample.md --filter /home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py  -o _build/test.pdf
Traceback (most recent call last):
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 260, in <module>
    main()
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 257, in main
    toJSONFilters([tip])
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 59, in toJSONFilters
    altered = reduce(lambda x, action: walk(x, action, format, meta), actions, doc)
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 59, in <lambda>
    altered = reduce(lambda x, action: walk(x, action, format, meta), actions, doc)
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 83, in walk
    x[k] = walk(x[k], action, format, meta)
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 72, in walk
    array.append(walk(item, action, format, meta))
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 83, in walk
    x[k] = walk(x[k], action, format, meta)
  File "/home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py", line 70, in walk
    res = action(item['t'], item['c'], format, meta)
KeyError: 'c'
pandoc: Error running filter /home/damien/dev/github/daamien/pandoc-latex-tip/pandoc_latex_tip.py
Filter returned error status 1
```

**Comment by daamien** [comment]
FIX here : https://github.com/chdemko/pandoc-latex-tip/pull/5
